export const images = {
  alarm_icon: require("./alarm_icon.png"),
  astronout_sleep: require("./astronout_sleep.png"),
  bed_icon: require("./bed_icon.png"),
  bell_alarm: require("./bellalarm_icon.png"),
  bigclock: require("./bigclock.png"),
  check_icon: require("./check_icon.png"),
  facebook_icon: require("./facebook_icon.png"),
  google_icon: require("./google_icon.png"),
  home_icon: require("./home_icon.png"),
  moon_icon: require("./moon_icon.png"),
  reject_icon: require("./reject_icon.png"),
  main_background: require("./main_background.png"),
  statistics_icon: require("./statistics_icon.png"),
  welcome_background: require("./welcome_background.png"),
};
